In [25]:
from nba_api.stats.endpoints import commonplayerinfo
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder
import requests

In [22]:
# Basic Request
player_info = commonplayerinfo.CommonPlayerInfo(player_id=2544)

In [23]:
nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
lakers = [team for team in nba_teams if team['abbreviation'] == 'LAL'][0]
lakers_id = lakers['id']
lakers

{'id': 1610612747,
 'full_name': 'Los Angeles Lakers',
 'abbreviation': 'LAL',
 'nickname': 'Lakers',
 'city': 'Los Angeles',
 'state': 'California',
 'year_founded': 1948}

In [24]:
# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=lakers_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612747,LAL,Los Angeles Lakers,0022000608,2021-03-15,LAL @ GSW,W,240,128,...,0.760,7,39,46,36,9,3,19,25,31.0
1,22020,1610612747,LAL,Los Angeles Lakers,0022000585,2021-03-12,LAL vs. IND,W,239,105,...,0.769,6,38,44,20,10,5,15,20,5.0
2,22020,1610612747,LAL,Los Angeles Lakers,0022000551,2021-03-03,LAL @ SAC,L,240,120,...,0.714,15,26,41,27,7,3,11,19,-3.0
3,22020,1610612747,LAL,Los Angeles Lakers,0022000542,2021-03-02,LAL vs. PHX,L,240,104,...,0.765,5,29,34,18,6,8,12,23,-10.0
4,22020,1610612747,LAL,Los Angeles Lakers,0022000527,2021-02-28,LAL vs. GSW,W,238,117,...,0.684,14,46,60,22,14,6,19,21,26.0

In [20]:
# Subset the games to when the last 4 digits of SEASON_ID were 2019.
games_1920 = games[games.SEASON_ID.str[-4:] == '2019']
games_1920.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
43,42019,1610612747,LAL,Los Angeles Lakers,0041900406,2020-10-11,LAL @ MIA,W,239,106,...,0.643,12,34,46,23,5,4,12,22,13.0
44,42019,1610612747,LAL,Los Angeles Lakers,0041900405,2020-10-09,LAL vs. MIA,L,240,108,...,0.857,12,29,41,21,10,5,15,21,-3.0
45,42019,1610612747,LAL,Los Angeles Lakers,0041900404,2020-10-06,LAL @ MIA,W,241,102,...,0.857,10,32,42,25,5,4,15,14,6.0
46,42019,1610612747,LAL,Los Angeles Lakers,0041900403,2020-10-04,LAL @ MIA,L,240,104,...,0.759,11,32,43,23,8,2,19,22,-11.0
47,42019,1610612747,LAL,Los Angeles Lakers,0041900402,2020-10-02,LAL vs. MIA,W,240,124,...,0.588,16,28,44,32,6,3,9,26,10.0

In [32]:
playergame = leaguegamefinder.LeagueGameFinder(player_id_nullable='2544')
playergame = playergame.get_data_frames()[0]
playergame

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612747,LAL,Los Angeles Lakers,0022000608,2021-03-15,LAL @ GSW,W,30,22,...,0.667,1,9,10,11,0,0,6,3,6.6
1,22020,1610612747,LAL,Los Angeles Lakers,0022000585,2021-03-12,LAL vs. IND,W,34,18,...,0.636,0,3,3,10,1,0,3,4,2.2
2,32020,1610616834,LBN,Team LeBron,0032000001,2021-03-07,LBN @ DRT,W,13,4,...,NaN,0,2,2,4,0,1,1,0,-0.6
3,22020,1610612747,LAL,Los Angeles Lakers,0022000542,2021-03-02,LAL vs. PHX,L,38,38,...,0.600,0,5,5,6,2,1,3,1,0.4
4,22020,1610612747,LAL,Los Angeles Lakers,0022000527,2021-02-28,LAL vs. GSW,W,24,19,...,0.500,2,4,6,4,2,2,2,2,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1661,22003,1610612739,CLE,Cleveland Cavaliers,0020300038,2003-11-01,CLE @ POR,L,39,8,...,1.000,0,4,4,6,2,0,2,3,-4.2
1662,22003,1610612739,CLE,Cleveland Cavaliers,0020300018,2003-10-30,CLE @ PHX,L,41,21,...,0.571,2,10,12,8,1,0,7,1,-0.6
1663,22003,1610612739,CLE,Cleveland Cavaliers,0020300014,2003-10-29,CLE @ SAC,L,42,25,...,0.333,2,4,6,9,4,0,2,3,-1.8
1664,12003,1610612739,CLE,Cleveland Cavaliers,0010300011,2003-10-08,CLE @ ATL,W,5,6,...,NaN,0,3,3,3,2,0,3,3,NaN
1665,12003,1610612739,CLE,Cleveland Cavaliers,0010300003,2003-10-07,CLE @ DET,W,5,8,...,NaN,0,3,3,7,1,2,3,2,NaN

In [36]:
playergame.to_csv('lebronstats.csv', index=False)
games_1920.to_csv('lakersstats.csv', index=False)